### ISSUE TITLE
Reset secondsOnSlide when changed event occurs

### ISSUE THREAD

**Issue by corbinchild** [dolbex/slither-slider#26]
Hi, great plugin.  Thank you.

I have noticed that the autoplay option does not adapt to the 'changed' event.  For example, if I set secondsOnSlide to 10 seconds, and then click the next slide arrow after 9 seconds, 1 second later the autoplay option will trigger and change the slide again.

It would be better if the secondsOnSlide timer is reset when the changed event occurs.  This way, each slide will be on screen for the full 10 seconds.

**Comment by dolbex** [comment]
Hey @corbinchild - good observation - adding in a fix for this today. Should see it within the next couple hours.

**Comment by dolbex** [comment]
Pushed out on 2.8.0
